### PR TITLE
work please

### PR DESCRIPTION
**Pull request by jinsoo601**
hello.py

### CODE REVIEW

**Comment by timothydmorton** [comment]
So this most likely works for you on windows, but just a tip that if you want an executable script to work on linux/mac, you will need the first line of the file to be:

    #!/usr/bin/env python

**Comment by jinsoo601** [comment]
Does that apply to all the python programs?

**Comment by jinsoo601** [comment]
Do I type that in the command prompt of the Linux computer? Or does that go
in the first line of python files?

**Comment by timothydmorton** [comment]
Yeah, that applies to all python programs you want to run from the command line.  That line should be the first line of the file.  When you're on your linux machine you can test this.

**Comment by jinsoo601** [comment]
I submitted word_prompter.py and resubmitted hello.py but now hello.py has
>>>>>day1-ex1 and some extra lines that I did not type in. Also, git push
origin day1-ex1 seems to be not working properly on my computer.

**Comment by jinsoo601** [comment]
Hi I just changed the executable permission for those three files which were under the master branch, but I do not know how to access day1-ex1 branch which contains other files. I think I accidently pulled all of Eve's work somehow? I am very confused.

**Pull request closed without merging**
